services:
  bot-service:
    image: node:20-alpine
    container_name: bot-service
    working_dir: ${DOCKER_PROJECT_DIR:-/usr/app}
    restart: unless-stopped
    environment:
      ENV: ${NODE_ENV:-dev}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      GUILD_ID: ${GUILD_ID:-}
      NODE_DOCKER_ENV: ${NODE_DOCKER_ENV:-20}
      DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR:-/usr/app}
      EXPRESS_PORT: ${EXPRESS_PORT:-3000}
      MONGO_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_DB: ${MONGO_DB:-satoro_bot}
    volumes:
      - ./:${DOCKER_PROJECT_DIR:-/usr/app}
      - ./node_modules:${DOCKER_PROJECT_DIR:-/usr/app}/node_modules
    ports:
      - ${NODE_PORT:-80}:8080
    command: npm run ${NODE_ENV:-dev}
